org: eternity
app: scheduled-tg-bot
service: quote-bot
useDotenv: true

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    NOTION_TOKEN: ${param:NOTION_TOKEN}
    NOTION_DATABASE_ID: ${param:NOTION_DATABASE_ID}
    BOT_TOKEN: ${param:BOT_TOKEN}
    CHAT_ID: ${param:CHAT_ID}

functions:
  cronHandler:
    handler: handler.run
    events:
      - schedule:
          rate: cron(0 9 * * ? *)
          enabled: true